CREATE TABLE image_prompt_template (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    template_code VARCHAR(128) NOT NULL,
    template_name VARCHAR(255) NOT NULL,
    template_type VARCHAR(32) NOT NULL,
    content_text LONGTEXT NOT NULL,
    enabled_flag BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_image_prompt_template_code (template_code),
    KEY idx_image_prompt_template_type (template_type, enabled_flag, sort_order),
    KEY idx_image_prompt_template_name (template_name)
);

CREATE TABLE image_generation_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    generation_type VARCHAR(32) NOT NULL,
    ai_setting_key VARCHAR(64) NOT NULL,
    provider_name VARCHAR(64),
    model_name VARCHAR(128),
    prompt_template_codes TEXT,
    negative_template_codes TEXT,
    positive_prompt_text LONGTEXT,
    negative_prompt_text LONGTEXT,
    final_prompt LONGTEXT NOT NULL,
    image_size VARCHAR(32),
    quality VARCHAR(32),
    output_format VARCHAR(32),
    background VARCHAR(32),
    moderation VARCHAR(32),
    response_format VARCHAR(32),
    input_fidelity VARCHAR(32),
    user_text VARCHAR(128),
    image_count INT NOT NULL DEFAULT 1,
    source_image_file_name VARCHAR(255),
    source_image_path VARCHAR(512),
    source_image_content_type VARCHAR(128),
    source_image_size BIGINT,
    mask_image_file_name VARCHAR(255),
    mask_image_path VARCHAR(512),
    mask_image_content_type VARCHAR(128),
    mask_image_size BIGINT,
    result_file_name VARCHAR(255),
    result_file_path VARCHAR(512),
    result_file_content_type VARCHAR(128),
    result_file_size BIGINT,
    status VARCHAR(32) NOT NULL,
    request_payload LONGTEXT,
    response_payload LONGTEXT,
    error_message TEXT,
    started_at DATETIME,
    finished_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_image_generation_status_time (status, created_at),
    KEY idx_image_generation_setting_time (ai_setting_key, created_at),
    KEY idx_image_generation_type_time (generation_type, created_at)
);
