CREATE TABLE requirement_module_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    module_no VARCHAR(64) NOT NULL,
    project_code VARCHAR(64) NOT NULL,
    title VARCHAR(256) NOT NULL,
    requirement_desc TEXT,
    priority VARCHAR(32),
    status VARCHAR(32) NOT NULL,
    source VARCHAR(128),
    parent_requirement_no VARCHAR(64) NOT NULL,
    root_requirement_no VARCHAR(64) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    main_agent_code VARCHAR(64),
    session_strategy VARCHAR(32),
    preferred_session_code VARCHAR(64),
    current_stage VARCHAR(64),
    expected_deadline DATETIME,
    created_by VARCHAR(64),
    execution_steps TEXT,
    execution_mode VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    result_extractable_flag BOOLEAN NOT NULL DEFAULT TRUE,
    review_required_flag BOOLEAN NOT NULL DEFAULT FALSE,
    review_approved_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_requirement_module_no (module_no),
    KEY idx_requirement_module_root_sort (root_requirement_no, sort_no, status),
    KEY idx_requirement_module_parent_sort (parent_requirement_no, sort_no),
    KEY idx_requirement_module_project_root (project_code, root_requirement_no),
    KEY idx_requirement_module_agent_status (main_agent_code, status, sort_no)
);

INSERT INTO requirement_module_info (
    id,
    module_no,
    project_code,
    title,
    requirement_desc,
    priority,
    status,
    source,
    parent_requirement_no,
    root_requirement_no,
    sort_no,
    main_agent_code,
    session_strategy,
    preferred_session_code,
    current_stage,
    expected_deadline,
    created_by,
    execution_steps,
    execution_mode,
    result_extractable_flag,
    review_required_flag,
    review_approved_flag,
    created_at,
    updated_at
)
SELECT
    id,
    requirement_no,
    project_code,
    title,
    requirement_desc,
    priority,
    status,
    source,
    COALESCE(parent_requirement_no, root_requirement_no),
    root_requirement_no,
    sort_no,
    main_agent_code,
    session_strategy,
    preferred_session_code,
    current_stage,
    expected_deadline,
    created_by,
    execution_steps,
    execution_mode,
    result_extractable_flag,
    review_required_flag,
    review_approved_flag,
    created_at,
    updated_at
FROM requirement_info
WHERE requirement_type = 'SUB';

DELETE FROM requirement_info
WHERE requirement_type = 'SUB';
