CREATE TABLE project_knowledge_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_code VARCHAR(64) NOT NULL,
    knowledge_type VARCHAR(32) NOT NULL,
    title VARCHAR(256) NOT NULL,
    simple_desc VARCHAR(1024) NULL,
    detail_content LONGTEXT NULL,
    organized_content LONGTEXT NULL,
    confirmed_content LONGTEXT NULL,
    source_requirement_no VARCHAR(64) NULL,
    source_summary LONGTEXT NULL,
    ai_setting_key VARCHAR(64) NULL,
    embedding_setting_key VARCHAR(64) NULL,
    document_ids VARCHAR(1024) NULL,
    selected_similar_knowledge_id BIGINT NULL,
    selected_similar_score DOUBLE NULL,
    status VARCHAR(32) NOT NULL,
    vector_status VARCHAR(32) NOT NULL,
    vector_dirty_flag BOOLEAN NOT NULL DEFAULT TRUE,
    vector_collection VARCHAR(128) NULL,
    vector_id VARCHAR(128) NULL,
    vector_file_path VARCHAR(512) NULL,
    vector_updated_at DATETIME NULL,
    error_message VARCHAR(4000) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_project_knowledge_project (project_code),
    INDEX idx_project_knowledge_type (knowledge_type),
    INDEX idx_project_knowledge_source_req (source_requirement_no),
    INDEX idx_project_knowledge_vector_status (vector_status)
);
